title: Lerntagebuch BAIN
author: Remo
email: remo.bischoff@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Bibliotheks- und Archivinformatik HS2020

# social links
github_username:  remooda # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
